name = "Travelogue"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = "A simple, adaptable blog theme using featured images"
homepage = "http://www.oldmanexploring.com/"
tags = ["blog","travel"]
features = ["blog"]
min_version = "0.34"

[author]
  name = "Christopher Curtis"
  homepage = "http://www.chriscurtis.co.uk"
